### PR TITLE
Clean front end

### PR DESCRIPTION
**Pull request by JonasAlaif**

### CODE REVIEW

**Comment by JonasAlaif** [comment]
Fix a bug where achievements got werent loaded at start so could get the same achievement multiple times

**Comment by JonasAlaif** [comment]
Actually Im not sure about some of the changes in the achievements scripts, is that from Unity collab? @Bhorda

**Comment by Bhorda** [comment]
You need to ignore the whole AR folder, the ones on git are correct

**Comment by JonasAlaif** [comment]
Should be fine now, I had to make a few changes to your scripts with how they interact with the network database since I changed how the completed achievements are strored.
There should be no major changes to any of your or Raz's scripts though.

**Pull request merged**
